Завдання 1.
Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть
його значення

In [21]:
import numpy as np

arr3 = np.arange(2, 21, 2)
print("3:", arr3)

3: [ 2  4  6  8 10 12 14 16 18 20]


Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
дійсними числами від 0 до 1 та виведіть його значення.

In [22]:
import numpy as np

# Створення матриці 3x3 з випадковими числами від 0 до 1
matrix = np.random.rand(3, 3)

# Виведення значень матриці
print(matrix)


[[0.88520313 0.90053207 0.53223525]
 [0.9434785  0.52944737 0.07034673]
 [0.21804795 0.86775703 0.19676025]]


Завдання 3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 20 та виведіть його значення.

In [23]:
import numpy as np

# Створення матриці 3x3 з випадковими натуральними числами від 1 до 20
matrix = np.random.randint(1, 21, size=(3, 3))

# Виведення значень матриці
print(matrix)


[[16 12  7]
 [11  1  5]
 [ 9  8 11]]


Завдання 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть мінімальний елемент.

In [24]:
import numpy as np

# Створення матриці 4x4 з випадковими числами від 0 до 1
matrix = np.random.rand(4, 4)

# Виведення значень матриці
print("Матриця:\n", matrix)

# Знаходження мінімального елемента
min_value = np.min(matrix)
print("Мінімальний елемент:", min_value)


Матриця:
 [[0.69599373 0.37692632 0.05249865 0.29904447]
 [0.46637809 0.65419994 0.18221126 0.83702998]
 [0.52118043 0.10170334 0.74342939 0.76766202]
 [0.75950521 0.55359209 0.03047616 0.44305863]]
Мінімальний елемент: 0.03047616209646209


Завдання 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від 1 до 15 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [25]:
import numpy as np

# Створення двох масивів розміром 7 з випадковими цілими числами від 1 до 15
array1 = np.random.randint(1, 16, size=7)
array2 = np.random.randint(1, 16, size=7)

# Виведення значень масивів
print("Масив 1:", array1)
print("Масив 2:", array2)

# Поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення результатів
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [ 2 10  3 12  8  6 12]
Масив 2: [11  9  2 13  5  8 10]
Додавання: [13 19  5 25 13 14 22]
Віднімання: [-9  1  1 -1  3 -2  2]
Множення: [ 22  90   6 156  40  48 120]


Завдання 6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та
знайдіть їх добуток.

In [26]:
import numpy as np

# Створення двох матриць 3x3 з випадковими цілими числами від 3 до 30
matrix1 = np.random.randint(3, 31, size=(3, 3))
matrix2 = np.random.randint(3, 31, size=(3, 3))

# Виведення значень матриць
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)

# Обчислення добутку матриць
product = np.dot(matrix1, matrix2)

# Виведення результату
print("Добуток матриць:\n", product)


Матриця 1:
 [[ 7 26 25]
 [ 3  8 21]
 [12 17 28]]
Матриця 2:
 [[17 14  4]
 [27 19 10]
 [19 28 11]]
Добуток матриць:
 [[1296 1292  563]
 [ 666  782  323]
 [1195 1275  526]]


Завдання 7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою

In [27]:
import numpy as np

# Створення матриці 4x2 з випадковими цілими числами від 1 до 7
matrix1 = np.random.randint(1, 8, size=(4, 2))

# Створення матриці 2x5 з випадковими цілими числами від 1 до 7
matrix2 = np.random.randint(1, 8, size=(2, 5))

# Виведення значень матриць
print("Матриця 4x2:\n", matrix1)
print("Матриця 2x5:\n", matrix2)

# Обчислення добутку матриць
product = np.dot(matrix1, matrix2)

# Виведення результату
print("Добуток матриць:\n", product)


Матриця 4x2:
 [[6 4]
 [2 6]
 [2 5]
 [3 6]]
Матриця 2x5:
 [[7 1 2 6 3]
 [2 5 3 5 7]]
Добуток матриць:
 [[50 26 24 56 46]
 [26 32 22 42 48]
 [24 27 19 37 41]
 [33 33 24 48 51]]


Завдання 8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.


In [28]:
import numpy as np

# Створення матриці 2x2 з випадковими цілими числами від 1 до 8
matrix = np.random.randint(1, 9, size=(2, 2))

# Виведення значень матриці
print("Матриця:\n", matrix)

# Перевірка на наявність оберненої матриці (матриця повинна бути невиродженою)
if np.linalg.det(matrix) != 0:
    # Обчислення оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:\n", inverse_matrix)
else:
    print("Матриця є виродженою, обернена матриця не існує.")


Матриця:
 [[6 2]
 [4 6]]
Обернена матриця:
 [[ 0.21428571 -0.07142857]
 [-0.14285714  0.21428571]]


Завдання 9. Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [29]:
import numpy as np

# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Виведення значень матриці
print("Матриця:\n", matrix)

# Транспонування матриці
transposed_matrix = matrix.T

# Виведення транспонованої матриці
print("Транспонована матриця:\n", transposed_matrix)


Матриця:
 [[0.08304862 0.10638265 0.58892118]
 [0.31166665 0.44657524 0.09292588]]
Транспонована матриця:
 [[0.08304862 0.31166665]
 [0.10638265 0.44657524]
 [0.58892118 0.09292588]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор

In [30]:
import numpy as np

# Створення матриці 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створення вектора 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))

# Виведення значень матриці та вектора
print("Матриця:\n", matrix)
print("Вектор:\n", vector)

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

# Виведення результату
print("Добуток матриці на вектор:\n", product)


Матриця:
 [[ 1  9  3 10]
 [ 3  6  8  4]
 [ 2  5  4  2]]
Вектор:
 [[1]
 [8]
 [5]
 [4]]
Добуток матриці на вектор:
 [[128]
 [107]
 [ 70]]


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.


In [31]:
import numpy as np

# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Виведення значень матриці та вектора
print("Матриця:\n", matrix)
print("Вектор:\n", vector)

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

# Виведення результату
print("Добуток матриці на вектор:\n", product)


Матриця:
 [[0.78561362 0.75602574 0.36872573]
 [0.66665012 0.37988499 0.86755785]]
Вектор:
 [[4]
 [2]
 [9]]
Добуток матриці на вектор:
 [[ 7.97303756]
 [11.23439108]]


Завдання 12. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.

In [32]:
import numpy as np

# Створення двох матриць 4x4 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Виведення значень матриць
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)

# Обчислення суми матриць
sum_matrix = matrix1 + matrix2

# Виведення результату
print("Сума матриць:\n", sum_matrix)


Матриця 1:
 [[ 5  4  1  9]
 [ 3  3  3  8]
 [ 2  5  9  7]
 [10  5  6  4]]
Матриця 2:
 [[ 9  5  6  5]
 [ 9  3  1  5]
 [ 4  7 10  8]
 [10  5  9  6]]
Сума матриць:
 [[14  9  7 14]
 [12  6  4 13]
 [ 6 12 19 15]
 [20 10 15 10]]


Завдання 13. Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть їх добуток.

In [33]:
import numpy as np

# Створення двох матриць 4x4 з випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, size=(4, 4))
matrix2 = np.random.uniform(-1, 1, size=(4, 4))

# Виведення значень матриць
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)

# Обчислення добутку матриць
product = np.dot(matrix1, matrix2)

# Виведення результату
print("Добуток матриць:\n", product)


Матриця 1:
 [[-0.12277231 -0.03070895  0.2108605   0.71197649]
 [-0.25575707  0.37276715  0.62771368  0.4195382 ]
 [ 0.24809424  0.84987559  0.81048685 -0.07026869]
 [-0.98898517  0.68889611 -0.95113222 -0.81224144]]
Матриця 2:
 [[ 0.92798364 -0.23430743  0.4776395   0.72544429]
 [-0.78008672  0.1915358   0.20224488  0.42668686]
 [ 0.88669642  0.76135455  0.95790194 -0.03005399]
 [-0.42235432 -0.64579036  0.20366271  0.69542621]]
Добуток матриць:
 [[-0.20371214 -0.27636335  0.28213512  0.38662234]
 [-0.14873138  0.33830298  0.63996301  0.2464099 ]
 [ 0.31558481  0.76709797  1.05243841  0.46938425]
 [-1.95547262  0.16406369 -1.40956738 -0.9597794 ]]


Завдання 14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть суму елементів матриці

In [34]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, size=(3, 3))

# Виведення значень матриці
print("Матриця:\n", matrix)

# Обчислення суми елементів матриці
sum_of_elements = np.sum(matrix)

# Виведення результату
print("Сума елементів матриці:", sum_of_elements)


Матриця:
 [[-0.95600639 -0.76899484 -0.99855052]
 [ 0.29201729 -0.96484968  0.79217198]
 [-0.78485458 -0.84334725  0.58914134]]
Сума елементів матриці: -3.6432726482755453


Завдання 15. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів
кожного рядка матриці.


In [35]:
import numpy as np

# Створення матриці 5x5 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))

# Виведення значень матриці
print("Матриця:\n", matrix)

# Обчислення суми елементів кожного рядка
row_sums = np.sum(matrix, axis=1)

# Перетворення на вектор-стовпчик
row_sums_column_vector = row_sums.reshape(-1, 1)

# Виведення результату
print("Вектор-стовпчик сум елементів кожного рядка:\n", row_sums_column_vector)


Матриця:
 [[-0.30743817  0.05668998 -0.24601301 -0.03192902 -0.01417838]
 [ 0.09168171  0.28248498  0.05931406  0.47563037  0.25472028]
 [ 0.09771768  0.06246357 -0.21564382 -0.13709201  0.14551198]
 [-0.42060778  0.43713185 -0.28457413 -0.08958405 -0.06182678]
 [-0.12600734 -0.03882819 -0.13125624 -0.08516357  0.05093214]]
Вектор-стовпчик сум елементів кожного рядка:
 [[-0.54286859]
 [ 1.1638314 ]
 [-0.04704261]
 [-0.41946089]
 [-0.33032319]]


Висновок. У всіх завданнях ми навчились генерувати матриці та вектори різних розмірів, заповнюючи їх випадковими числами. Це може бути як цілими числами, так і дійсними числами, що дозволяє адаптувати результати під різні потреби. Отримані навички можуть бути корисні для аналізу даних, обробки сигналів, комп'ютерної графіки, машинного навчання та інших галузей, де використовуються матричні операції.